from __future__ import annotations

from app.models import RecruiterProfile, Scenario

SCENARIOS: list[Scenario] = [
    Scenario(
        id="fintech-backend",
        company="LedgerLoop",
        title="Senior Backend Engineer for fintech infra",
        brief="Hiring a senior backend engineer in fintech who has scaled event-driven systems, knows LangGraph or agent orchestration, and can partner closely with product. NYC hybrid preferred, but open to strong remote candidates in EST. Need recruiter help this month.",
        stage="Scorecards drifting between recruiter inboxes and hiring manager feedback loops.",
        urgency="critical",
        team_size="42 employees",
        location="New York City / EST",
    ),
    Scenario(
        id="healthtech-gtm",
        company="CareMesh",
        title="Founding GTM recruiter for healthtech expansion",
        brief="Need a fractional recruiter to help hire two senior account executives and one growth marketer for a Series A healthtech startup selling to provider groups. Must know healthcare compliance nuances and build personalized outreach. Remote across the US is fine.",
        stage="Pipeline volume is decent, but on-site loops are thin and closing is inconsistent.",
        urgency="high",
        team_size="28 employees",
        location="Remote US",
    ),
    Scenario(
        id="ai-product",
        company="PromptLayer Labs",
        title="Product lead for AI workflow platform",
        brief="Looking for a product leader who has shipped AI workflow tools, ideally with SaaS PLG experience, strong customer empathy, and exposure to prompt tooling. San Francisco hybrid strongly preferred. Need a recruiter with product network depth.",
        stage="Inbound interest is noisy and PM calibration is not consistent across interviewers.",
        urgency="high",
        team_size="65 employees",
        location="San Francisco",
    ),
    Scenario(
        id="developer-relations",
        company="StackOrbit",
        title="Developer relations lead for open-source infra",
        brief="Hiring a senior developer relations lead with strong content chops, open-source credibility, and ability to run community programs. Europe-friendly time zones are a plus. Want a recruiter who understands technical storytelling and community talent.",
        stage="Strong top-of-funnel, but the team is unsure how to evaluate community impact consistently.",
        urgency="medium",
        team_size="18 employees",
        location="Remote / Europe-friendly",
    ),
    Scenario(
        id="ops-fractional",
        company="ParcelPilot",
        title="Fractional operator for recruiting engine cleanup",
        brief="We need a fractional recruiting operator who can clean up our ATS, manage agency coordination, and close an operations manager plus senior analyst for a logistics startup. Chicago hybrid preferred. Need someone embedded, metrics-minded, and fast.",
        stage="The team has recruiter partners, but no single owner is driving ATS hygiene and candidate throughput.",
        urgency="critical",
        team_size="55 employees",
        location="Chicago",
    ),
]

RECRUITERS: list[RecruiterProfile] = [
    RecruiterProfile(
        id="r1",
        name="Maya Chen",
        firm="Northstar Talent",
        tagline="Embedded fintech and infra recruiting partner for seed to Series C teams.",
        recruiter_type="fractional",
        industries=["fintech", "infrastructure", "b2b saas"],
        role_focus=["backend engineer", "platform engineer", "engineering manager"],
        seniority_focus=["senior", "staff", "lead"],
        skills=["python", "distributed systems", "kafka", "langgraph", "llm", "microservices"],
        locations=["new york", "boston", "remote us"],
        remote_friendly=True,
        fee_percentage=18,
        placements_last_12_months=24,
        avg_time_to_slate_days=6,
        fill_rate=0.82,
        active_search_capacity=3,
        languages=["English", "Mandarin"],
        notable_clients=["Mercury", "Alloy", "Rho"],
        bio="Former in-house recruiting lead for two fintech startups; known for structured calibration and tight founder communication.",
    ),
    RecruiterProfile(
        id="r2",
        name="Jordan Alvarez",
        firm="Signal Recruit",
        tagline="Go-to-market and commercial hiring specialist for regulated software teams.",
        recruiter_type="marketplace",
        industries=["healthtech", "fintech", "b2b saas"],
        role_focus=["account executive", "growth marketer", "sales leader"],
        seniority_focus=["senior", "director"],
        skills=["sales hiring", "demand gen", "healthcare compliance", "outbound"],
        locations=["remote us", "austin", "new york"],
        remote_friendly=True,
        fee_percentage=20,
        placements_last_12_months=31,
        avg_time_to_slate_days=5,
        fill_rate=0.79,
        active_search_capacity=4,
        languages=["English", "Spanish"],
        notable_clients=["Commure", "Ramp", "Abridge"],
        bio="Specializes in high-signal GTM hiring where narrative quality and close partnership matter.",
    ),
    RecruiterProfile(
        id="r3",
        name="Priya Raman",
        firm="Craft Product Search",
        tagline="Product and design recruiter with deep AI and PLG network density.",
        recruiter_type="fractional",
        industries=["ai", "developer tools", "b2b saas"],
        role_focus=["product manager", "product lead", "design lead"],
        seniority_focus=["senior", "lead", "head"],
        skills=["ai products", "plg", "user research", "product strategy"],
        locations=["san francisco", "remote us", "seattle"],
        remote_friendly=True,
        fee_percentage=19,
        placements_last_12_months=18,
        avg_time_to_slate_days=7,
        fill_rate=0.76,
        active_search_capacity=2,
        languages=["English"],
        notable_clients=["Notion", "Retool", "Scale AI"],
        bio="Trusted by founders for product searches that require technical fluency and nuanced story-selling.",
    ),
    RecruiterProfile(
        id="r4",
        name="Elena Petrova",
        firm="Community Signal",
        tagline="Developer relations and community talent partner across open-source ecosystems.",
        recruiter_type="marketplace",
        industries=["developer tools", "open source", "cloud infrastructure"],
        role_focus=["developer relations", "community manager", "solutions engineer"],
        seniority_focus=["senior", "lead"],
        skills=["developer relations", "content", "community", "open source", "technical storytelling"],
        locations=["remote europe", "remote uk", "berlin"],
        remote_friendly=True,
        fee_percentage=17,
        placements_last_12_months=14,
        avg_time_to_slate_days=8,
        fill_rate=0.74,
        active_search_capacity=3,
        languages=["English", "Russian"],
        notable_clients=["Sentry", "Supabase", "Temporal"],
        bio="Pairs outbound recruiting with community mapping to uncover credibility-first candidates.",
    ),
    RecruiterProfile(
        id="r5",
        name="Samir Patel",
        firm="Operator Bench",
        tagline="Fractional recruiting operator for ATS cleanup, analytics, and execution rigor.",
        recruiter_type="embedded",
        industries=["logistics", "marketplaces", "operations tech"],
        role_focus=["operations manager", "bizops", "analyst"],
        seniority_focus=["senior", "manager"],
        skills=["ats operations", "reporting", "process design", "logistics", "stakeholder management"],
        locations=["chicago", "remote us", "denver"],
        remote_friendly=True,
        fee_percentage=16,
        placements_last_12_months=22,
        avg_time_to_slate_days=4,
        fill_rate=0.85,
        active_search_capacity=5,
        languages=["English", "Hindi"],
        notable_clients=["Flexport", "ShipBob", "Project44"],
        bio="Best fit when a startup needs both recruiter leverage and ATS operating discipline.",
    ),
    RecruiterProfile(
        id="r6",
        name="Olivia Grant",
        firm="Frontline Talent Co.",
        tagline="Generalist startup recruiter with balanced technical and GTM coverage.",
        recruiter_type="marketplace",
        industries=["b2b saas", "ai", "fintech"],
        role_focus=["backend engineer", "product manager", "account executive"],
        seniority_focus=["mid", "senior"],
        skills=["sourcing", "interview process", "candidate experience", "outreach"],
        locations=["remote us", "los angeles", "new york"],
        remote_friendly=True,
        fee_percentage=18,
        placements_last_12_months=27,
        avg_time_to_slate_days=7,
        fill_rate=0.72,
        active_search_capacity=6,
        languages=["English"],
        notable_clients=["Webflow", "Airtable", "Figma"],
        bio="A strong all-around option when the search needs speed and polished candidate comms.",
    ),
]
